/** Permission keys used to authorize production-order and nested resource routes. */
export const PRODUCTION_ORDER_PERMISSIONS = {
  LIST: 'production-orders.list',
  READ: 'production-orders.read',
  EXPORT: 'production-orders.export',
  EXPORT_WEIGHING_TICKET: 'production-orders.export-weighing-ticket',
  EXPORT_WAREHOUSE_RELEASE: 'production-orders.export-warehouse-release',
  DOCUMENT_CONTROL_UPDATE: 'production-orders.document-control.update',
  CREATE: 'production-orders.create',
  UPDATE: 'production-orders.update',
  DELETE: 'production-orders.delete',
  SEND_SAMPLING_REQUEST: 'production-orders.sampling-requests.send',
  STEAM_STERILIZATION_READ: 'production-orders.steam-sterilization-checks.read',
  STEAM_STERILIZATION_CREATE: 'production-orders.steam-sterilization-checks.create',
  STEAM_STERILIZATION_UPDATE: 'production-orders.steam-sterilization-checks.update',
  STEAM_STERILIZATION_DELETE: 'production-orders.steam-sterilization-checks.delete',
  MATERIAL_SUMMARY_READ: 'production-orders.material-summaries.read',
  MATERIAL_SUMMARY_CREATE: 'production-orders.material-summaries.create',
  MATERIAL_SUMMARY_UPDATE: 'production-orders.material-summaries.update',
  MATERIAL_SUMMARY_DELETE: 'production-orders.material-summaries.delete',
  UPLOAD_PRODUCTION_GUIDE: 'production-orders.production-guide.upload',
  FILTRATION_CHECK_READ: 'production-orders.filtration-checks.read',
  FILTRATION_CHECK_CREATE: 'production-orders.filtration-checks.create',
  FILTRATION_CHECK_UPDATE: 'production-orders.filtration-checks.update',
  FILTRATION_CHECK_DELETE: 'production-orders.filtration-checks.delete',
} as const;
