-- CreateTable
CREATE TABLE `business_partners` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `card_code` VARCHAR(191) NOT NULL,
    `card_name` TEXT NOT NULL,
    `card_type` VARCHAR(30) NOT NULL,
    `group_code` INTEGER NULL,
    `tax_code` VARCHAR(255) NULL,
    `foreign_name` TEXT NULL,
    `address` TEXT NULL,
    `custom_address` TEXT NULL,
    `city` VARCHAR(255) NULL,
    `country_code` VARCHAR(10) NULL,
    `phone` VARCHAR(255) NULL,
    `phone_secondary` VARCHAR(255) NULL,
    `mobile` VARCHAR(255) NULL,
    `email` VARCHAR(255) NULL,
    `contact_person` VARCHAR(255) NULL,
    `is_valid` BOOLEAN NULL,
    `valid_from` DATE NULL,
    `valid_to` DATE NULL,
    `is_frozen` BOOLEAN NULL,
    `frozen_from` DATE NULL,
    `frozen_to` DATE NULL,
    `notes` TEXT NULL,
    `partner_origin` VARCHAR(255) NULL,
    `custom_partner_label` VARCHAR(255) NULL,
    `custom_contact_person` VARCHAR(255) NULL,
    `custom_phone` VARCHAR(255) NULL,
    `sap_created_date` DATE NULL,
    `sap_created_time` VARCHAR(20) NULL,
    `sap_updated_date` DATE NULL,
    `sap_updated_time` VARCHAR(20) NULL,
    `last_synced_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `business_partners_card_code_key`(`card_code`),
    INDEX `business_partners_card_type_card_code_idx`(`card_type`, `card_code`),
    INDEX `business_partners_group_code_idx`(`group_code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
